### ISSUE TITLE
Failure mode: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/phrosty#36]
sn="20000104" 
ra="8.167274983711236" 
dec="-43.08698868442529" 
band="Y106" 

After ~40  min. 

```
Traceback (most recent call last):
  File "/global/cfs/cdirs/m4385/users/lauren/phrosty/phrosty/pipeline.py", line 559, in <module>
    main()
  File "/global/cfs/cdirs/m4385/users/lauren/phrosty/phrosty/pipeline.py", line 555, in main
    pipeline( args.through_step )
  File "/global/cfs/cdirs/m4385/users/lauren/phrosty/phrosty/pipeline.py", line 465, in __call__
    sfftifier = self.align_and_pre_convolve( templ_image, sci_image )
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4385/users/lauren/phrosty/phrosty/pipeline.py", line 206, in align_and_pre_convolve
    sfftifier.resampling_image_mask_psf()
  File "/global/cfs/cdirs/m4385/users/lauren/sfft/sfft/SpaceSFFTCupyFlow.py", line 132, in resampling_image_mask_psf
    PixA_Eobj_GPU, EProjDict = CR.frame_extension(XX_proj_GPU=XX_proj_GPU,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/global/cfs/cdirs/m4385/users/lauren/sfft/sfft/utils/ResampKits.py", line 344, in frame_extension
    RMIN = (math.floor(XX_proj_GPU.min().item()) - 1) - KERHW[0]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: cannot convert float NaN to integer
```

**Comment by laldoroty** [comment]
Have to verify this, but it seems like if it fails like this for one SN in one band, it fails like this for all the other bands as well.

**Comment by laldoroty** [comment]
This happens when the template and science image are the same image, which sometimes happens for the modified NN2 method that Bastien and I are working on.

**Comment by rknop** [comment]
In fact, the solution might be putting in a check that none of the template images are science images and vice versa, and throwing an exception if they are.

**Comment by laldoroty** [comment]
Closing due to being incredibly stale.
